### ISSUE TITLE
User icon is broken only using the IconFont

### ISSUE THREAD

**Issue by guillaumewttj** [WTTJ/welcome-ui#1002]
###  Describe the bug

User icon is broken only using the IconFont

### To Reproduce

```
<IconFont name="user" />
```

### Expected behavior

User icon should look the same when using font or SVGs

### Environment

- `@welcome-ui/icons.font` [3.13.1]

### Additional context/Screenshots
Visible on the docs: https://www.welcome-ui.com/components/icons-font

**Comment by theo-mesnil** [comment]
Same issue https://github.com/WTTJ/welcome-ui/issues/942
