### ISSUE TITLE
Theme typography

### ISSUE THREAD

**Issue by Jademhm** [WTTJ/welcome-ui#1272]
Todo:

- new naming XS S M etc, remove useless variants...

**Comment by Jademhm** [comment]
https://www.notion.so/wttj/Typography-e0354c6f5c354accb8707e249e93346a

**Comment by theo-mesnil** [comment]
@Jademhm here you can find the documentation to review https://v5-typography--welcome-ui.netlify.app/components/text

**Comment by Jademhm** [comment]
Looks good but how do I check that you've put the right sizes and line-heights? Also do you have to put the line-height in rem for responsive?

**Comment by theo-mesnil** [comment]
@Jademhm yes is for accessibility :) for testing you can use the selector on chrome, i can show you if you want :)
