### ISSUE TITLE
Update Pagination

### ISSUE THREAD

**Issue by VictorWTTJ** [WTTJ/welcome-ui#1273]
Update Pagination component 

[Figma file](https://www.figma.com/file/AvmwrkaddJDjI4L5Mg8q0A/Global-items?node-id=106%3A1922)

Spec :
[Figma Spec](https://www.figma.com/file/AvmwrkaddJDjI4L5Mg8q0A/Global-items?node-id=787%3A3510)

Use `Small secondary black rounded button` for active page - Use `Small ghost rounded button ` otherwise

**Comment by RobelTekle** [comment]
Component preview : 
https://feat-pagination-1273--welcome-ui.netlify.app/components/pagination

**Comment by VictorWTTJ** [comment]
Hello, sur la UI on est OK 👍 

Par contre sur la UX on a un truc pas super agréable globalement. Lorsqu'on utilise la Truncation, on ne devrait pas avoir des pages qui s'ajoutent puis se suppriment.

https://user-images.githubusercontent.com/51406731/182656234-d6d7891f-74dd-47ab-a490-b5a52b522d90.mov

Du coup on devrait avoir plutôt ça :
First = < **1** 2 3 4 5 … 34 >
Before double truncation = < 1 2 3 **4** 5 … 34 >
First Double truncation =  < 1 … 4 **5** 6 … 34 >
Last Double truncation = < 1 … 29 **30** 31 … 34 >
Last = < 1 … 30 31 32 33 **34** >
On a donc toujours 9 items

Du coup est-ce qu'il y a pas un bug sur le RangeDisplay ?

**Comment by RobelTekle** [comment]
Hello 👋 
j'ai fait l'update. https://feat-pagination-1273--welcome-ui.netlify.app/components/pagination
@VictorWTTJ dit moi si besoin d'autres modifications

**Comment by VictorWTTJ** [comment]
Yo @RobelTekle 
En effet à partir du moment où on a la truncation, l'effet de transition fait un joli clignotement pas super agréable, je serai d'avis de le supprimer.

**Comment by RobelTekle** [comment]
@VictorWTTJ je vais enlever la transition, à part ça est-ce que le reste c'est good pour toi ?

**Comment by VictorWTTJ** [comment]
@RobelTekle C'est parfait merci !
