### ISSUE TITLE
Update Dialog/Modal

### ISSUE THREAD

**Issue by theo-mesnil** [WTTJ/welcome-ui#1349]
### Dialog/Modal

- [Figma file](https://www.figma.com/file/TC5aahnPVDU1hhBcff037e/Feedback?node-id=8%3A1515)
- [Documentation & spec.](https://www.notion.so/wttj/Modal-Dialog-95670726216a43bead80f3ca90aefc41)

**Comment by Louiseaks** [comment]
Mes retours sur la modal: 

- Lorsqu'il y a un icon en header celui-ci doit être en 40px 
- Il n'y a jamais de divider dans le footer sauf si le body dépasse la taille de la modale
- Je me pose la question du "close" qui me parait énorme, même si les tailles sont exactes - est-ce qu'on ne mettrais pas du 12px à la place du 16px ? 
- Visuellement je trouve qu'il y a un problème de spacing entre le header et le body donc je mettrais le spacing bottom du header à 0px pour avoir juste 16px et non 24px (cf. exemple ci-dessous)
<img width="743" alt="Capture d’écran 2022-09-01 à 13 46 53" src="https://user-images.githubusercontent.com/104991726/187906630-4dcb1124-c090-4306-ba08-81ec4b697bbc.png">

Sinon le reste est nickel ! À dispo pour en discuter en live :)

**Comment by Leiksa** [comment]
@Louiseaks C'est corrigé, je te laisse checker sur le même lien pour voir si tout est ok pour toi ! 💃

**Comment by Louiseaks** [comment]
@Leiksa Parfait pour moi ! Merci ☺️
