### ISSUE TITLE
Border radius on shape

### ISSUE THREAD

**Issue by Geminii** [WTTJ/welcome-ui#1461]
Result : 
![Image](https://user-images.githubusercontent.com/9429420/182390491-280f72e0-4f0a-465c-b339-98989b2c3300.png)

Expected : 
It should apply border radius on the shape

**Comment by theo-mesnil** [comment]
@Geminii it's because on the welcome theme we put the borderRadius to 0 to remove it on all components

**Comment by Geminii** [comment]
Oh ok, it's a little bit confusing so 😅 (and we can't have this information without checking the configuration theme 🙈)

In this example, we probably need to force it to add the border no ? Otherwise the example loses its interest because it seems that the property does not apply. What do you think about it ?
