### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by Jademhm** [WTTJ/welcome-ui#1465]
[Link to figma](https://www.figma.com/file/TC5aahnPVDU1hhBcff037e/Feedback?node-id=2%3A2777)

**Comment by theo-mesnil** [comment]
@Jademhm de notre côté sur nos tooltip le texte est en blanc (light.900), on ferait pareil ici ou on est pas bon côté wttj ?

**Comment by theo-mesnil** [comment]
@Jademhm dispo ici https://v5-tooltip-1465--welcome-ui.netlify.app/components/tooltip pour le test

**Comment by Jademhm** [comment]
Ça me paraît top mais manque l'anim sur le fixed?

**Comment by Isaacmaamouche** [comment]
J'avais désactivé le translate dans le cas le tooltip est soit fixed soit en placement auto. 
Pour le auto, je peux pas prédire la position qu'il aura et donc garantir que le translate se fasse dans la bonne direction, mais je te laisse le dernier mot !
Pour le fixed par contre j'ai oublié 🙃 je l'ai réactivé.

**Comment by Jademhm** [comment]
Sinon on peut kill l'animation sur le tracked tooltip 👍 

Ça me paraît good mais il y a pas le détails des différentes positions d'apparitions possibles ? (avec les animations correspondantes selon le placement)

**Comment by Isaacmaamouche** [comment]
@Jademhm 
- Pas d'animation si le tooltip n'est pas fixed ✅ 
- Doc mise à jour avec des exemples selon le placement ✅ 

https://v5-tooltip-1465--welcome-ui.netlify.app/components/tooltip

**Comment by Jademhm** [comment]
Impecc, manque juste la spécificité pour les placements bottom/top où on peut aligné à gauche et à droite en plus de la position centrale par défaut 👀

**Comment by Isaacmaamouche** [comment]
@Jademhm 
J’ai update pour gérer toutes les directions possibles pour l’animation  + j'ai rajouté les cas dans la doc
[https://v5-tooltip-1465--welcome-ui.netlify.app/components/tooltip](https://v5-tooltip-1465--welcome-ui.netlify.app/components/tooltip)
