### ISSUE TITLE
Callout

### ISSUE THREAD

**Issue by Jademhm** [WTTJ/welcome-ui#1468]
[Link to Figma](https://www.figma.com/file/TC5aahnPVDU1hhBcff037e/Feedback?node-id=2%3A2778)

**Comment by Leiksa** [comment]
@Jademhm Tu peux checker le design ici https://v5-callout--welcome-ui.netlify.com/

**Comment by Jademhm** [comment]
Seems good to me but isn't there a variant missing? The one without title and only the description or the description + CTA?

**Comment by Leiksa** [comment]
I can still add an example for this case, but the <Alert.Title /> component isn't mandatory, you can try to remove it from the code editor to see the Alert without title and only with description or description + CTA.
Don't hesitate to tell me if you want that I add this example in the documentation. 😄
