### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by VictorWTTJ** [WTTJ/welcome-ui#1470]
[Link to Figma](https://www.figma.com/file/jAg2mzxXFZocK1MZOmX6IA/Data-display?node-id=3%3A1789)

**Comment by theo-mesnil** [comment]
@VictorWTTJ review dispo ici : https://v5-accordion-1470--welcome-ui.netlify.app/

**Comment by VictorWTTJ** [comment]
Hello @theo-mesnil @Isaacmaamouche 

Mes retours :
- Title de l'accordion devrait être un H5 en WelcomeFont.
- Pas les bons spacings (mais j'imagine que c'est normal pour l'instant?) : j'ai du 20px et un -10 en margin sur le body. Y'a tous les spacings margin dans le doc.
- J'ai essayé d'intégrer un icon en lg, pas l'impression non plus que la size soit la bonne (24px logiquement pour l'icone ou avatar).
-Moyen d'utiliser le component button ghost en small pour le arrow ? Je pense que ça éviterait le glitch pas ouf liée à l'animation (vraiment du détail donc pas grave si pas corrigé).

**Comment by VictorWTTJ** [comment]
En effet my bad, j'ai cliqué sur le lien mis par Théo et comme je tombais pas sur le composant direct j'ai utilisé la search qui me faisait tombé sur l'ancien composant :)
Du coup bah c'est OK, merci !
