### ISSUE TITLE
Tag

### ISSUE THREAD

**Issue by VictorWTTJ** [WTTJ/welcome-ui#1471]
[Link to Figma](https://www.figma.com/file/jAg2mzxXFZocK1MZOmX6IA/Data-display?node-id=3%3A22)

**Comment by Geminii** [comment]
Element missing : 
- primary spec (for background and border color)
- subs spec (for background and border color)
- text selection background color ? always yellow ?
- smooth transition effect between state hover ?

**Comment by theo-mesnil** [comment]
#1503

**Comment by theo-mesnil** [comment]
@VictorWTTJ to test :

https://feat-tag-component--welcome-ui.netlify.com/

**Comment by VictorWTTJ** [comment]
@theo-mesnil Nice ! 

Pas la bonne couleur pour le label du `default` qui doit être en Nude900.
Dans la logique pour les subs on devrait avoir le label en Light900 sur les sub 2,3 et 6 - Dark900 sur les subs 1,4,5 et 7.

**Comment by theo-mesnil** [comment]
@Geminii ⬆️

**Comment by Geminii** [comment]
@VictorWTTJ feedbacks have been handled 😇

Can you check again ? 🙏 (same previous link)
