### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by Jademhm** [WTTJ/welcome-ui#1472]
[Link to Figma](https://www.figma.com/file/JrPBB5pItDO43GhHE7pT3K/Navigation?node-id=2%3A3)

**Comment by theo-mesnil** [comment]
@Jademhm tu peux testée ici https://feat-tabs--welcome-ui.netlify.app/

**Comment by Jademhm** [comment]
Here's the feedback:
* **Font size**
    * Medium → Body M = 16px
    * Small → Body S = 14px (≠ 16px currently)
* **Underline**
	* Not supposed to be 3px but 2px
* **Paddings**
    * Font from bottom → 12px for both sizes
    * Currently there’s 16px on Medium and 8px on Small
* **Colour**
    * Disabled → I don’t know what the colour is in the inspect, it returns me "rgba(0, 0, 0, 0.55)" which would be Dark 500 in our design records but it’s supposed to be Light 700 (#B3B3B3)

**Comment by Vico4** [comment]
>   * Disabled → I don’t know what the colour is in the inspect, it returns me "rgba(0, 0, 0, 0.55)" which would be Dark 500 in our design records but it’s supposed to be Light 700 (#B3B3B3)

@Jademhm Light 700 works only on dark theme (it's white with a transparency so it appears white on the doc), is there a light theme color that fits ? Dark 500 was the closest visually. 
For everything else I do it today, thank you :)

**Comment by Jademhm** [comment]
Default = Dark 700
Disabled = Dark 400
