### ISSUE TITLE
Slider

### ISSUE THREAD

**Issue by Jademhm** [WTTJ/welcome-ui#1473]
[Link to Figma](https://www.figma.com/file/l9klusKgMYIp90BkLBE3K7/Forms?node-id=146%3A4104)

**Comment by theo-mesnil** [comment]
Pour l'animation reprendre le style de https://polaris.shopify.com/components/range-slider

**Comment by theo-mesnil** [comment]
@Jademhm dispo ici https://v5-slider--welcome-ui.netlify.app/components/slider pour la review :)

**Comment by Jademhm** [comment]
Sur le côté UI ça me paraît all good par contre manque l'animation et la possibilité de voir le tooltip, comme sur Shopify

**Comment by Leiksa** [comment]
@Jademhm, animation ajouté tu peux check quand tu veux sur le même lien qu'au dessus :)

**Comment by Jademhm** [comment]
Moyen d'être un peu plus smooth sur le tooltip et de faire un scale 0 to 100 depuis le bas avec fade in ?

**Comment by Leiksa** [comment]
Yess corrigé désolé ! Ça devrait être good :) @Jademhm

**Comment by Jademhm** [comment]
Seems all good pour moi ✨
