### ISSUE TITLE
Rework Toast component

### ISSUE THREAD

**Issue by theo-mesnil** [WTTJ/welcome-ui#1647]
Replace the package `toasted-notes` because it is no longer maintained

**Comment by Calvein** [comment]
FYI, it'll prevent us to beneficiate from using react 18 bonuses

> Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
