### ISSUE TITLE
Link

### ISSUE THREAD

**Issue by Jademhm** [WTTJ/welcome-ui#1717]
**Context:** Rework of the links setting principles, themes and a new animation.

[Link to Figma](https://www.notion.so/wttj/Link-b7bf662641ff40a3a1bcfe6a342153d6)

**Comment by theo-mesnil** [comment]
Helloooo @Jademhm 

Demo here https://feat-link--welcome-ui.netlify.app/components/link 🥳

**Comment by Jademhm** [comment]
Seems alrighty but just a slight concern about the margins behaviour as described on the Notion documentation. It seems the links are aligned starting from the underline which they are not supposed to be?

**Comment by theo-mesnil** [comment]
@Jademhm yes, is good now :)
