### ISSUE TITLE
Breadcrumb

### ISSUE THREAD

**Issue by Jademhm** [WTTJ/welcome-ui#1776]
[Link to Figma](https://www.figma.com/file/JrPBB5pItDO43GhHE7pT3K/Navigation?node-id=351%3A2082)

Documentation on Notion not completed but can be dev without it

**Comment by DuarteParadela** [comment]
@Jademhm Ready to be tested https://feat-breadcrumb--welcome-ui.netlify.app/components/breadcrumb

**Comment by Jademhm** [comment]
All good pour moi 👌🏼
