### ISSUE TITLE
Update Forms

### ISSUE THREAD

**Issue by theo-mesnil** [WTTJ/welcome-ui#1811]
https://github.com/WTTJ/welcome-ui/issues/1361#issuecomment-1369513681
From @Pauline999

Coucou ✌🏼, quelques composants qu'il reste à ajuster sur les précédents feedbacks + Toogle (new) :) 

### File drop

- Il manque le `dashed` sur le contour.

### Checkbox

- Le spacings entre la "Checkbox + label" et le hint est **OK**  par contre j’ai l’impression que ça à mécaniquement réduit le spacing entre le **Checkbox** et la L**abel (ou icone + label)** qui est passé à 4px alors que c’est 8px.
- Réduire le spacing entre les items dans une liste = 12px **-> KO C'est bien 12px dans le code mais le rendu fais plutôt 24px, si on passe la marge en front à 4px(0.25rem) on tombe pile poile sur 12px coté rendu.**

### Radio button

- Margin `horizontal alignment` entre les radio en ligne = 16px (****Column style)****
- Spacing entre le radio button et le Hint = 4px

### **Clearable (select, field, etc)**

- Impec pour l’update du rollover par contre sur l’input text /select/date picker etc en **`xs`** (height à 24px) il faut qu’on adapte la taille du hover gris uniquement pour le passer à 16px pour éviter qu’il touche le contours du field.

### Hook Form

- Appliquer spacing de 16px entre les components dans un form. **> KO Le margin de 16px n'est pas appliqué entre le field email et lacheckbox et la checkbox et le bouton**

## Toogle

- Focus state: change the color to #FFE166 et passer la taille du contour de 3px à 2px
- Faire le changement du passage du contour de 3px à 2px pour tous les composants field/select/radio etc

**Comment by Pauline999** [comment]
Impec 🔥 merci pour les updates, j'ai remarqué 3 petits détails  :) 

**File drop**
Il y a une différence de rendu sur l'espacement du `dashed `sur le contour. Dash à 4px et gap à 4px coté figma :) 

**Radio Button**
Petit bug d'alignement horizontal, ce n'est pas centré entre le label et la liste de radio buttons 

**Toggle**
Oops c'est la couleur du background qui semble avoir été changée alors qu'il s'agit de la couleur du contour comm les autres focus (j'avais pas précisé🙃)

**Comment by Vico4** [comment]
@Pauline999 merci pour tes retours :) 
Pour le filedrop c'est pas possible de customiser les spacings du dashed en css, est-ce qu'on peut rester sur la version actuelle ? 
Le reste c'est fait.
