### ISSUE TITLE
Checkbox Indeterminate state

### ISSUE THREAD

**Issue by Pauline999** [WTTJ/welcome-ui#1842]
Add indeterminate state for checkboxs -> Used in a hierarchy of checkboxes, when not all children are checked, the parent remains indeterminate
- [Figma](https://www.figma.com/file/l9klusKgMYIp90BkLBE3K7/Forms?node-id=614%3A6401&t=00Hu3b7ckxKUftbD-1)
- [Notion](https://www.notion.so/wttj/Checkbox-1f3c17ff899f443aa9040718442b552a)

**Comment by Vico4** [comment]
@Pauline999 : pour le petit tiret du indeterminate j'ai exporté le svg du figma mais est-ce que ce serait possible d'avoir un export avec un path et pas un rect stp ?

**Comment by Pauline999** [comment]
![icon-indeterminate](https://user-images.githubusercontent.com/96482129/212092110-82b17f51-3b34-498f-b99f-e1fc541d1d34.svg)
Like this :) ?

**Comment by Pauline999** [comment]
![indeterminate-icon](https://user-images.githubusercontent.com/96482129/212096961-048e2532-ee02-4e58-b244-3b6d5f197991.svg)

**Comment by Pauline999** [comment]
![icon-indeterminate](https://user-images.githubusercontent.com/96482129/212097640-da5a3c14-cfaf-4d0f-9b99-ff67caf4fdef.svg)
