### ISSUE TITLE
`<Link />` does not forward props to React Router's `<Link />`

### ISSUE THREAD

**Issue by ligaz** [WTTJ/welcome-ui#1977]
###  Describe the bug

React Router's [`<Link />`](https://reactrouter.com/en/main/components/link) component supports `relative` property. However this property is not forwarded from the Welcome UI's `<Link />` component, when the router's Link is used as `as` prop.

### To Reproduce
```js
<Link
  as={RouterLink}
  to=".."
  relative="path" 
/>
```

### Expected behavior

The prop should be forwarded to the `as` component.

### Additional context
After debugging the issue it looks like `relative` is not forwarded as it is not part of the standard and system attributes. By accident the `to` prop is forwarded as it is an [SVG animate attribute](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/To).

**Comment by theo-mesnil** [comment]
Hi @ligaz ,

Sorry for the delay, we will check this but i think the problem is from @xstyled, who does not pass the props to the child.

I'll keep you updated if we've got a fix.

**Comment by theo-mesnil** [comment]
Hi @ligaz ,

We will removed in the future (start 2024) [@xstyled](https://github.com/styled-components/xstyled), who will fixed this issue. I close now this PR, sorry for this.
