### ISSUE TITLE
Call out with CTA on mobile 

### ISSUE THREAD

**Issue by Pauline999** [WTTJ/welcome-ui#2066]
Hola 🪁

Sur mobile on a un petit soucis de responsive avec le layout qui n'est pas adapté lorsqu'il y a un texte de bouton un peu long.
Est-ce qu'on pourrait envisager une solution pour éviter cela ? du style :

- Si le bouton dépasse 'n' px de largeur (ou 50% de la largeur) on effectue un passage à ligne du bouton et le title + description passent en full largeur.
- Ou donner la possibilité au dev via une option d'activer le passage à la ligne du bouton ? 

À dispo pour s'en parler 😉. 
Pauline

Exple avec le screenshot ici  :

![Capture d’écran 2023-05-10 à 14 45 03](https://github.com/WTTJ/welcome-ui/assets/96482129/c58c5945-5413-49a8-b78a-34fa060a07f1)

**Comment by theo-mesnil** [comment]
Close for now, will be reopen :)
