### ISSUE TITLE
Checkbox, radio button and toggle - align hint

### ISSUE THREAD

**Issue by aurelienalletru** [WTTJ/welcome-ui#2143]
### For which component?

Checkbox, radio button, toggle

### Description

Align the hint with label and not with the checkbox or radio

### Due Date

unknown

### Design documentation
[Checkbox](https://www.notion.so/wttj/Checkbox-1f3c17ff899f443aa9040718442b552a?pvs=4)
[Radio button](https://www.notion.so/wttj/Radio-button-1d8608d8bd6144b5b3a7830fffb8e24a?pvs=4)
[Toggle](https://www.notion.so/wttj/Toggle-6c6945d9fd9c415c83fb072aeb656a62?pvs=4)

### Change 
Checkbox hint aligned with label
Radio button hint aligned with label
Toggle resized width : 26px -> 24px
Toggle hint aligned with label

**Comment by aurelienalletru** [comment]
To Review : 

1. Checkbox hint aligned with label
2. Radio button hint aligned with label
3. Toggle resized width : 26px -> 24px
4. Toggle hint aligned with label

Can you check my branch please before 29/08 night ? 
[Branch is here](https://www.figma.com/file/l9klusKgMYIp90BkLBE3K7/branch/dveEiTceoEIn6aKf8K6Bmk/Forms?type=design&mode=design&t=V9Wz6EtqizbZbk82-1)

thanks 
Mandatory
@VictorWTTJ 

Others
@Jademhm 
@Pauline999 
@Louiseaks

**Comment by aurelienalletru** [comment]
@theo-mesnil @mleralec 
On va devoir mettre à jour les check box, radio button et toggle, pouvez-vous me confirmer la faisabilité technique et passer le ticket à  "To Document" quand c'est OK pour vous :) ? 
Voici les changements : 

1. Checkbox hint aligned with label
2. Radio button hint aligned with label
3. Toggle resized width : 26px -> 24px
4. Toggle hint aligned with label

Merci :)

**Comment by theo-mesnil** [comment]
@aurelienalletru ✅

**Comment by aurelienalletru** [comment]
Please check the design documentation. 
I have updated all images.

[Checkbox](https://www.notion.so/wttj/Checkbox-1f3c17ff899f443aa9040718442b552a?pvs=4)
[Radio button](https://www.notion.so/wttj/Radio-button-1d8608d8bd6144b5b3a7830fffb8e24a?pvs=4)
[Toggle](https://www.notion.so/wttj/Toggle-6c6945d9fd9c415c83fb072aeb656a62?pvs=4)

Mandatory review :) 
@VictorWTTJ 

Others
@Jademhm 
@Pauline999 
@Louiseaks 

Due date 5/09 night  

Thx

**Comment by VictorWTTJ** [comment]
Good for me !

**Comment by clairepaillier** [comment]
Ok aussi @aurelienalletru !

**Comment by Pauline999** [comment]
To Review after rollback of **Forms Library**  :

- Checkbox hint aligned with label
- Radio button hint aligned with label
- Toggle resized width : 26px -> 24px
- Toggle hint aligned with label

Can you check my branch please ?
[Branch is here](https://www.figma.com/file/l9klusKgMYIp90BkLBE3K7/branch/buojk1I1kh1OaF4Vc6IykN/Forms?type=design&node-id=2%3A6939&mode=design&t=zbe2uLi5sg9rLX9r-1)

thanks
@aurelienalletru 
@Jademhm
@VictorWTTJ

**Comment by aurelienalletru** [comment]
@Pauline999 All is good in my side. Merci bcp !

**Comment by Jademhm** [comment]
@Pauline999 ✅

**Comment by theo-mesnil** [comment]
@aurelienalletru you can review this issue on https://feat-new-checkable-style--welcome-ui.netlify.app/

**Comment by aurelienalletru** [comment]
@theo-mesnil 
All is OK for me ! ✅ Thx :)

**Comment by VictorWTTJ** [comment]
Good !!

**Comment by theo-mesnil** [comment]
@aurelienalletru je te laisse approved la PR et la merger ? :p
