### ISSUE TITLE
Tabs - more spacing

### ISSUE THREAD

**Issue by aurelienalletru** [WTTJ/welcome-ui#2144]
### For which component?

Tabs

### Description

More spacing between tabs (1,5rem)

### Due Date

unknown

**Comment by Jademhm** [comment]
Tabs always have `24px` of paddings in-between them.

We increased from `12px` to `24px` on the `small` size.

[See the spacings on Figma](https://www.figma.com/file/JrPBB5pItDO43GhHE7pT3K/Navigation?type=design&node-id=119-1860&mode=design&t=I1jdsRsOCius7fow-11)

**Comment by theo-mesnil** [comment]
@Jademhm ✅
