### ISSUE TITLE
Text area : text-state Value - Height adaptation broken

### ISSUE THREAD

**Issue by Pauline999** [WTTJ/welcome-ui#2154]
### For which Figma library?

Forms

### For which component?

Textarea

### Current Behavior

1. Le composant est cassé (WYSUWYG aussi) quand on change le text-state : de Placeholder à Value le texte reste sur une seule ligne. Le component `_Input / Content` perd l'attribut "fill" sur la hauteur.
2. Aussi lorsqu'on ajoute une icône ou image celle ci se centre sur la hauteur

![Capture d’écran 2023-07-31 à 16 45 03](https://github.com/WTTJ/welcome-ui/assets/96482129/e3d6b10b-b62c-4257-b9fe-7295a8c89b43)
![Capture d’écran 2023-07-31 à 16 47 35](https://github.com/WTTJ/welcome-ui/assets/96482129/710a4b23-35d1-4ece-b46c-46d02fd72e2f)
![Capture d’écran 2023-07-31 à 16 47 39](https://github.com/WTTJ/welcome-ui/assets/96482129/fcaa35f8-da21-4a52-af86-408475e2f3ac)

### Expected Behavior

1. Le texte soit s'adapter sur la hauteur et revenir à la ligne automatiquement. `_Input / Content` doit garder l'attribut "fill" sur la hauteur.
2. Garder l'icone ou l'image positionnés en haut à gauche

![Capture d’écran 2023-07-31 à 16 52 25](https://github.com/WTTJ/welcome-ui/assets/96482129/8fe99018-568f-4d8a-a05e-803afa77760f)

**Comment by Pauline999** [comment]
C'est corrigé ✌🏼, si vous voulez tester le "Text area" avant que je publie @Jademhm @aurelienalletru, risque que ça impact aussi les fields et selects car le composant .` _Input / Content` est commun 
https://www.figma.com/file/l9klusKgMYIp90BkLBE3K7/Forms?type=design&node-id=2-6941&mode=design

**Comment by aurelienalletru** [comment]
@Pauline999 lorsque je suis sur la props Value et que je change avec/sans icon alors le texte dans n'est pas le même. 

https://github.com/WTTJ/welcome-ui/assets/109659230/42aa5444-2aac-4096-911e-6885c339b969

**Comment by aurelienalletru** [comment]
Le reste semble okay ✅ :) merci @Pauline999

**Comment by Pauline999** [comment]
Merci, bien vu ! c'est fix @aurelienalletru ;)

**Comment by VictorWTTJ** [comment]
Petit problème lors du resize. Rien de drama, mais j'ai pas réussi à identifier le pourquoi du comment…

https://github.com/WTTJ/welcome-ui/assets/51406731/04d2efc5-14be-4ac0-afa3-5937e90ac3a9

**Comment by Pauline999** [comment]
Merci, j'ai pu corriger le problème ✅ , ça venait d'une différence de 1px sur la largeur d'un des variants..
