### ISSUE TITLE
Slider Component: input number and slider bar are disconnected

### ISSUE THREAD

**Issue by RobelTekle** [WTTJ/welcome-ui#2168]
### For which component?

Slider

### Description

- When the slider is disabled we can change the value from the number input, press enter, and the slider will update
- When we change the value from the number input the slider bar update only if user press enter. The onChange event is not fired.

https://github.com/WTTJ/welcome-ui/assets/33298885/cbfd2667-987a-4e21-b9f1-653cc09f30c2

### Welcome UI Version

5.0.0-alpha.43

### Operating System

None

**Comment by theo-mesnil** [comment]
Hello @RobelTekle !

Thanks for the issue, i'll let you fix it please ?
