### ISSUE TITLE
Buttons font issue on Safari

### ISSUE THREAD

**Issue by malikWTTJ** [WTTJ/welcome-ui#2169]
### For which component?

Button

### Description

When navigation on WTTJ on safari 16.5.2, all buttons have an unexpected size and boldness.
Ex :  
![image](https://github.com/WTTJ/welcome-ui/assets/89013273/e20a40cc-3784-4436-a421-e2413ee3cbfc)

### Welcome UI Version

5.0.0-alpha.43

### Browser

Safari 16.5.2

### Operating System

MacOS

**Comment by theo-mesnil** [comment]
Hi,

This this an issue with the new work sans variable font and some components on safari, will check this asap.

Thanks for the issue :)
