### ISSUE TITLE
Bug button type change (Ghost -> Tertiary)

### ISSUE THREAD

**Issue by Louiseaks** [WTTJ/welcome-ui#2179]
### For which Figma library?

Basics

### For which component?

Button

### Current Behavior

Pas de changement du type de bouton

### Expected Behavior

Je souhaite transformer un bouton Tertiary en Ghost 

### Screenshots / Videos

[

https://github.com/WTTJ/welcome-ui/assets/104991726/3434065b-ce86-4205-894d-04364795ff26

](url)

**Comment by aurelienalletru** [comment]
Est-ce que c'est un bug qui revient souvent ?

**Comment by theo-mesnil** [comment]
@Jademhm @Louiseaks  on ferme ?
