### ISSUE TITLE
Border radius on tags

### ISSUE THREAD

**Issue by clairepaillier** [WTTJ/welcome-ui#2191]
### For which component?

Tag

### Description

In the context of improving our job pages, I'd like to take this opportunity to discuss with the design team to update our tags component. 

**Proposed changes :** 

- Border radius: 4px
- Removal of 1px gray stroke around tag

<img width="931" alt="Screenshot 2023-08-16 at 14 21 30" src="https://github.com/WTTJ/welcome-ui/assets/126099637/8a4df4a2-f790-4591-87c1-381e7106a6fc">

### Due Date

01/09/2023

**Comment by theo-mesnil** [comment]
It's comoing :)
