### ISSUE TITLE
Tooltip - Add 1px stroke to align with DS

### ISSUE THREAD

**Issue by Pauline999** [WTTJ/welcome-ui#2198]
### Prioritization

Low 😎

### Description

It miss a 1px stroke #4C4C4C on tooltip to be align with Design system → Needed for Sidebar on project one
https://www.welcome-ui.com/components/tooltip

Issue on WUI
![Capture d’écran 2023-08-17 à 12 19 44](https://github.com/WTTJ/welcome-ui/assets/96482129/1494e317-2d48-46d8-a301-3704fd8b269b)

Expected - Mockup
![Capture d’écran 2023-08-17 à 12 21 39](https://github.com/WTTJ/welcome-ui/assets/96482129/e4f236be-6ffe-4ad0-8c4a-9f3dd2008478)

**Comment by theo-mesnil** [comment]
@Pauline999 j'aurais besoin de la couleur light que je dois mettre please au dessus du noir :)

**Comment by Pauline999** [comment]
@theo-mesnil Nickel pour le dark-700merci :)

**Comment by theo-mesnil** [comment]
@Pauline999 c'est testable ici : https://feat-tooltip-stroke--welcome-ui.netlify.app/

**Comment by Pauline999** [comment]
@theo-mesnil Sorry je ne vois pas l'ajout du contour du tooltip sur le lien de test que tu m'a envoyé  
![Capture d’écran 2023-09-13 à 18 17 53](https://github.com/WTTJ/welcome-ui/assets/96482129/1006c413-20b2-4a95-9920-3ff4fde32d96)

**Comment by theo-mesnil** [comment]
@Pauline999 sorry, now it's good :)

**Comment by Pauline999** [comment]
@theo-mesnil c'est le même link ? car pas de diff de mon coté :)  https://feat-tooltip-stroke--welcome-ui.netlify.app/

**Comment by theo-mesnil** [comment]
@Pauline999 yes is the same link, i have this:

<img width="797" alt="Capture d’écran 2023-09-15 à 10 21 08" src="https://github.com/WTTJ/welcome-ui/assets/50322149/ca606f4c-3b2f-4071-8120-353b943b1a20">

**Comment by Pauline999** [comment]
@theo-mesnil Merci, c'est good de mon coté sur cette URL,  : 
https://feat-tooltip-stroke--welcome-ui.netlify.app/components/tooltip
