### ISSUE TITLE
DropdownMenu: always hide on click

### ISSUE THREAD

**Issue by RobelTekle** [WTTJ/welcome-ui#2247]
### [Design] For which Figma library?

None

### For which component/foundations?

DropdownMenu

### Prioritization

Medium ⛰️

### Current Behavior

The DropdownMenu will always close when user click on an item of the dropdown. No need to use the `hide` method returned by the hook. This behavior prevent to have more complex use case like checkbox in the dropdown.

Workaround: use a `e.preventDefault()` in the onClick of DropdownMenu.Item

### Expected Behavior

The DropdownMenu should close when the `hide` method is called or on a click outside of the dropdown

### Screenshots / Videos

https://github.com/WTTJ/welcome-ui/assets/33298885/2edd70ca-54bc-4a79-8b85-7b8df2c9747f

### [Tech] Operating System

None

**Comment by RobelTekle** [comment]
@theo-mesnil maybe it’s better to add `hideOnClick={false}` directly to DropdownMenu component. We probably want the same behavior for each item, otherwise we can use the `hide` method in an Item onClick.

**Comment by theo-mesnil** [comment]
@RobelTekle i think we need to add on our way this new props. A dropdownMenu need to be closed on click, i think we gonna migrate to the new components when it will be available. I test on our squad and it's work

**Comment by RobelTekle** [comment]
@theo-mesnil my bad, I did not understood that `hideOnClick` prop was already available on DropdownMenu.Item. That's great 👍
Yes maybe we can juste add an example in the documentation

**Comment by theo-mesnil** [comment]
@RobelTekle Yes i'll do that tomorrow, tell me if this works for you :)

**Comment by RobelTekle** [comment]
yes it works 😸
