### ISSUE TITLE
[Modal] modal types doesn't use ariakit dialog types

### ISSUE THREAD

**Issue by jeromeraffin** [WTTJ/welcome-ui#2313]
### For which component/foundations?

Modal

### Prioritization

Medium ⛰️

### Description

The modal component is based on ariakit dialog component but we're not using the types from it.
For example if I want to use the backdrop props on the modal component, typescript gives us an error.
https://ariakit.org/examples/dialog-backdrop-scrollable#rendering-a-custom-backdrop

**Comment by alissiagelabert** [comment]
Once this ticket is solved decomment following tests:
- test_cypress/cypress/e2e/showcase/critical/Showcase - cover - picture - fullscreen.feature
- test_cypress/cypress/e2e/showcase/low/Showcase - preview link - close click outside.feature
- test_cypress/cypress/e2e/showcase/medium/Showcase - block video - play close.feature
