### ISSUE TITLE
Issue with the icon "thumbs"

### ISSUE THREAD

**Issue by clairepaillier** [WTTJ/welcome-ui#2340]
### [Design] For which Figma library?

Icons

### For which component/foundations?

Button

### Prioritization

High 🌋

### Current Behavior

I can't switch the variant up/down between thumbs up and thumbs down in the variant. 

Tested by Aurélien : create a new icon and variant -> it works

### Expected Behavior

Functional switch between the two icons

### [Tech] Operating System

None

**Comment by aurelienalletru** [comment]
@clairepaillier 
je viens de faire la modif du thumb, normalement ça devrait être bon, tu peux vérifier ? 
Je viens d'updater la lib wttj et la publier. :)

**Comment by clairepaillier** [comment]
@aurelienalletru oui tout fonctionne bien, merci ! :)
