### ISSUE TITLE
failed when deploy to vercel

### ISSUE THREAD

**Issue by jujutsucode** [WTTJ/welcome-ui#2355]
### [Design] For which Figma library?

None

### For which component/foundations?

InputText

### Prioritization

Medium ⛰️

### Current Behavior

the box doesnt display as expected like in the docs

### Expected Behavior

displayed like in the docs

### Screenshots / Videos

![failed](https://github.com/WTTJ/welcome-ui/assets/138183266/dbeb07f7-e976-47cc-899e-4ad8b7fa2605)

### [Tech] Operating System

Linux

**Comment by jujutsucode** [comment]
failed too when local build

**Comment by jujutsucode** [comment]
my source code is here https://gitlab.com/dwipr508/papyrus-nextjs13.4

**Comment by mleralec** [comment]
Can you provide a codesandbox/stackblitz please?

**Comment by jujutsucode** [comment]
Here is my codesanbox 
https://codesandbox.io/p/github/jujutsucode/Papyrus-next/main?import=true&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clohp2rct0007336jvazmjrsp%2522%252C%2522sizes%2522%253A%255B10%252C90%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clohp2rcs0003336jsggpuiia%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clohp2rct0005336j1c0gkn63%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clohp2rct0006336j65rkgj6m%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B60%252C40%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clohp2rcs0003336jsggpuiia%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clohp2rcr0002336jo1w12xk8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clohp2rcs0003336jsggpuiia%2522%252C%2522activeTabId%2522%253A%2522clohp2rcr0002336jo1w12xk8%2522%257D%252C%2522clohp2rct0006336j65rkgj6m%2522%253A%257B%2522id%2522%253A%2522clohp2rct0006336j65rkgj6m%2522%252C%2522activeTabId%2522%253A%2522clohp6w4h00qs336jox2o4jm2%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522ENV_SETUP%2522%252C%2522id%2522%253A%2522clohp2rpg000p336j963xi595%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clohp6w4h00qs336jox2o4jm2%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clohp2rct0005336j1c0gkn63%2522%253A%257B%2522id%2522%253A%2522clohp2rct0005336j1c0gkn63%2522%252C%2522activeTabId%2522%253A%2522clohp6s3200o6336jgkt5z8z8%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clohp2rcs0004336jpq0edq60%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clohp2s6a000recir4mbxa3lw%2522%257D%252C%257B%2522id%2522%253A%2522clohp566j00gj336jlwvh788n%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clohp56ko000tecirbg1wgtzo%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%252C%2522id%2522%253A%2522clohp5w8900k2336jledalk1j%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clohp6s3200o6336jgkt5z8z8%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D
