### ISSUE TITLE
Add a link variant 

### ISSUE THREAD

**Issue by Pauline999** [WTTJ/welcome-ui#2381]
### For which component/foundations?

Link

### Prioritization

Low 🏖️

### Description

Add a link variant without underline on default state that can be used on lists for example. Keep the highlighting animation on hover (yellow/black/ color variation for article.)

### [Tech] Implementation

https://www.welcome-ui.com/components/link

**Comment by theo-mesnil** [comment]
Hello, un lien devrait toujours avoir un état underline pour que l'on puisse voir rapidement qu'il est cliquable et accessible, je trouve que c'est pas une bonne pratique personnellement.
