### ISSUE TITLE
Field with Phone number props

### ISSUE THREAD

**Issue by aurelienalletru** [WTTJ/welcome-ui#2409]
### For which component/foundations?

Field

### Prioritization

Low 🏖️

### Description

It would be nice to have a Phone number field with a country code selector.
The field should include a placeholder « Enter your number » and a persistent hint: Enter your number without the country code.
Impacts: Profile page, B2B account settings.

### [Tech] Implementation

Useful link here: https://louismazel.github.io/vue-phone-number-input/

**Comment by amelie-bresson** [comment]
https://wttj.atlassian.net/browse/WTTJ2-3062
