### ISSUE TITLE
Link "special case" in doc doesn't work

### ISSUE THREAD

**Issue by agriffis** [WTTJ/welcome-ui#637]
## 😭 Bug report 
The doc claims to show a Link with an alternative underline, but the alternative underline only works after clicking "Show Editor," and even then only on Firefox

###  Describe the bug
Navigate to http://welcome-ui.com/components/link

On Firefox and Chrome it looks like this:

<table><tr><td>

![image](https://user-images.githubusercontent.com/50637/82932780-f1259f80-9f56-11ea-8811-bf869c963e95.png)

</td></tr></table>

On Firefox if you click "Show Editor" it changes to the alternate underline:

<table><tr><td>

![image](https://user-images.githubusercontent.com/50637/82932819-039fd900-9f57-11ea-8c67-00d522904d49.png)

</td></tr></table>

On Chrome if you click "Show Editor" it doesn't change at all:

<table><tr><td>

![image](https://user-images.githubusercontent.com/50637/82932865-131f2200-9f57-11ea-9613-0abdfb7bce0d.png)

</td></tr></table>

### Expected behavior
Alternative underline should appear consistently without needing to click the button, right?

### Environment

- Browser: Firefox 76.0.1, Chrome 83.0.4103.61
- OS: Fedora 32
- Device: desktop

**Comment by theo-mesnil** [comment]
Hi, thanks for you feedback.

We are going to release in few days a new version of welcome-ui with the fix for this :)

I'll keep you in touch !

**Comment by theo-mesnil** [comment]
#642

**Comment by theo-mesnil** [comment]
It's now on https://github.com/WTTJ/welcome-ui/releases/tag/v2.0.0-alpha.17, thanks to @P1X3L and @guillaumewttj !
