### ISSUE TITLE
Field/layout.js violates xstyled doc

### ISSUE THREAD

**Issue by agriffis** [WTTJ/welcome-ui#681]
## 😭 Bug report 
I'm not sure how this bug expresses itself, but looking at the code, `Field/layout.js` seems to violate the xstyled documentation.

###  Describe the bug
Here you go:

https://github.com/WTTJ/welcome-ui/blob/09fb5874969078e10e31e787e14471d41cd466df/packages/Field/layout.js#L10-L14

but xstyled doc says:

![image](https://user-images.githubusercontent.com/50637/84421892-351cd380-abea-11ea-9da7-2a582090e549.png)

See https://xstyled.dev/docs/migrate-from-styled-components/#complete-css-property

It's possible that welcome-ui is doing something clever here that is proper and valid, but if that's the case, I would like to understand how. :smile:

**Comment by agriffis** [comment]
Seems like it should be more like this:

```javascript
export const FlexContainer = styled.div`
  ${props => css`
    flex: ${props.flex || null};
    flex-direction: ${props.direction || null};
  `};
  ${({align, direction, justify}) => getFlexStyles(align, justify, direction)};
`
```

**Comment by theo-mesnil** [comment]
Hi ! 
Thanks for you feedback, you're right we will check this soon :)

**Comment by theo-mesnil** [comment]
#642

**Comment by theo-mesnil** [comment]
https://github.com/WTTJ/welcome-ui/releases/tag/v2.0.0-alpha.17
