### ISSUE TITLE
Question : Sketch file including the components suite

### ISSUE THREAD

**Issue by abarre** [WTTJ/welcome-ui#718]
Thank you for open sourcing this internal UI kit.

I am currently looking for a design system that could have the UI component in React and also the component in sketch.
On this repo, I didn't find any associated sketch or figma file containing the components suite. 

Do you have a plan to open source the complete design system including a figma or sketch file ?
Also, is there any other company using the UI kit ? I wondering how easy it would be to rebrand it.

**Comment by theo-mesnil** [comment]
Hello :) 

Thanks for your interest on welcome ui 😍
Unfortunately it is not planned to share the associated sketch or figma file.
We don't know which company use our theme, but is easy to change the colors, rounded, spaces, fonts..., and you can go further for each components.
