### ISSUE TITLE
the close button of the Toast.Growl component overlaps its title

### ISSUE THREAD

**Issue by gdo-bzh** [WTTJ/welcome-ui#748]
###  Describe the bug

the close button of the Toast.Growl component overlaps the title when the body text length is lesser than the title length.

I am using Toast@2.0.0-alpha.31

### Expected behavior

The close button must not overlap the title whatever the length of the body text

### Additional context/Screenshots

![Screen Shot 2020-07-22 at 16 59 00](https://user-images.githubusercontent.com/67576908/88194011-98187600-cc3e-11ea-8dbb-8bdbfd7418ac.png)

**Comment by theo-mesnil** [comment]
Hi @gdo-bzh  !

Thanks for your issue, we will fix this soon :)

**Comment by guillaumewttj** [comment]
Hi @gdo-bzh ! 

This issue was fixed here: https://github.com/WTTJ/welcome-ui/pull/804
You can upgrade @welcome-ui/toast to 2.10.0 to get that fix :)
