### ISSUE TITLE
Breadcrumb rtl direction

### ISSUE THREAD

**Issue by StephaneRob** [WTTJ/welcome-ui#757]
###  Describe the bug

The rtl direction of the breacrumb is applied to the breadcrumb item too. This make the item reversed too.

![image](https://user-images.githubusercontent.com/4135765/88888069-e54ba780-d23d-11ea-98cb-96d454270520.png)

### Expected behavior

Should reset the direction on item?

### Environment

- `@welcome-ui/breadcrumb` 2.0.0
- `@welcome-ui/core` 2.0.0

**Comment by theo-mesnil** [comment]
Fixed on #758
