### ISSUE TITLE
Markdown Editor toolbar issue

### ISSUE THREAD

**Issue by StephaneRob** [WTTJ/welcome-ui#767]
###  Describe the bug

The last formatting selector is not applied in MarkdownEditor.

### To Reproduce

- go to https://www.welcome-ui.com/fields/markdown-editor
- in the example, select a word and apply formatting (bold, h1, h2...)
- Check the value => the formatting is not applied

### Expected behavior

Apply formatting

### Environment

- `@welcome-ui/markdown-editor` 2.0.2
- `@welcome-ui/core` 2.0.2

![image](https://user-images.githubusercontent.com/4135765/90141880-fa672100-dd7b-11ea-9bcd-ee11406eee72.png)

**Comment by theo-mesnil** [comment]
#769
