### ISSUE TITLE
Typescript declarations

### ISSUE THREAD

**Issue by msimonc** [WTTJ/welcome-ui#813]
Missing, unless I'm mistaken (not for the 1st time...)

Currently I @ts-ignore above each import...

Most projects have a separate @type/...  npm  but some manage to include in the component (ex. stripe)

**Comment by anucreative** [comment]
Hi @msimonc,

We've been talking about this (again) this week. Good to have a nudge. It's possible / probable we'll make a start on Typescript next week. We'll keep you posted. 👍🏼

**Comment by msimonc** [comment]
FYI there's a way to run 'tsc' on the command line to auto gen declaration files,

**Comment by theo-mesnil** [comment]
Hi @msimonc we have started to work on it : https://github.com/WTTJ/welcome-ui/pull/854

**Comment by theo-mesnil** [comment]
#856

**Comment by theo-mesnil** [comment]
https://github.com/WTTJ/welcome-ui/projects/1

**Comment by theo-mesnil** [comment]
Hi @msimonc , this will be on our v4 version, who is coming very soon :)

**Comment by msimonc** [comment]
Working
