### ISSUE TITLE
Avatar component should support custom `getInitials` function

### ISSUE THREAD

**Issue by tkhquang** [WTTJ/welcome-ui#839]
### Motivation

The current implementation of `getInitials` splits the name by non-word characters using the regex `/\W+/`, which may not be correct in some languages. For example, in Vietnamese, the name "Việt Nam" should be be displayed as "VN", not "VT". I would rather split characters by spaces instead of non-word characters in this case. So, I think it is reasonable to provide support for custom `getInitials` functions as some languages might be very different from others.

### Example

```jsx

function getInitials(name) {
  const formattedName = name && name.replace(/\s+/gm, ' ')
  let [firstWord, lastWord] = formattedName.split(' ')

  if (firstWord && lastWord) {
    return `${firstWord.charAt(0).toUpperCase()}${lastWord.charAt(0).toUpperCase()}`
  } else {
    return firstWord.substring(0, 2).toUpperCase()
  }
} 

<Avatar
  name="Việt Nam"
  size="sm"
  getInitials={getInitials}
/>

```

### Possible implementations

Add `getInitials` (or something like that) with default fallback for `Avatar` props.
I can help on this one if you support the idea of this.

**Comment by theo-mesnil** [comment]
Hi @tkhquang you can upgrade Avatar to 3.2.0 :)
https://github.com/WTTJ/welcome-ui/releases/tag/v3.2.0

**Comment by tkhquang** [comment]
@theo-mesnil  Thank you so much!  🍻
