### ISSUE TITLE
Warnings 

### ISSUE THREAD

**Issue by msimonc** [WTTJ/welcome-ui#851]
I'm getting this series of warnings for each @welcome component I yarn add:

warning " > @welcome-ui/box@2.15.3" has incorrect peer dependency "@xstyled/styled-components@^1.17.0".
warning " > @welcome-ui/box@2.15.3" has incorrect peer dependency "react@^16.10.2".
warning " > @welcome-ui/box@2.15.3" has incorrect peer dependency "react-dom@^16.10.2".
warning " > @welcome-ui/button@2.15.3" has incorrect peer dependency "@xstyled/styled-components@^1.17.0".

The web app still launches, but these warnings are new.

(@xstyled/styled-components has had a major release)

https://github.com/gregberge/xstyled/issues/270

**Comment by theo-mesnil** [comment]
#856
