### ISSUE TITLE
React Hook Form integration 

### ISSUE THREAD

**Issue by msimonc** [WTTJ/welcome-ui#878]
the default? use pattern for RHF looks like:

\<form onSubmit={handleSubmit}>
<InputText {...register("name")}/>
\</form>

which works fine but not for <ConnectedField component={DateTimePicker}...

I can't find \<HookForm/> (your docs) in their docs.

Thanks

**Comment by theo-mesnil** [comment]
Hi @msimonc, ConnectedField is for Final Form, we will rework this after our v4 with typescript.

You need to use Field, we use it with React Hook Form.
We will do an example for React Hook Form :)
