### ISSUE TITLE
Add AvatarStack component

### ISSUE THREAD

**Issue by Calvein** [WTTJ/welcome-ui#891]
### Motivation

We have the same component used in multiple product

### Example

![image](https://user-images.githubusercontent.com/243189/129687414-687c8806-e4cd-43bc-aa06-59171ce0b672.png)
![image](https://user-images.githubusercontent.com/243189/129687463-982d063d-aa24-42db-9c97-16061e8c4a5f.png)

### Possible implementations

TBD
e.g:
```jsx
<AvatarStack
  members={members}
  max={10}
/>
```

**Comment by iarmankhan** [comment]
I can pick up this component if no one is working on it.

**Comment by theo-mesnil** [comment]
Hi @iarmankhan😄 

We are currently creating it on the design team, we keep you in touch when it's going to be ready for developement. Thanks for your proposal 🙂
