### ISSUE TITLE
error on build (next.js)

### ISSUE THREAD

**Issue by msimonc** [WTTJ/welcome-ui#916]
all packages updated to latest,
(that's how I keep finding issues ;)
```		"@welcome-ui/core": "^3.5.0",```

error on build (next.js)
./node_modules/@welcome-ui/variant-icon/dist/variant-icon.es.js
Attempted import error: 'Box' is not exported from '@xstyled/styled-components' (imported as 'Box').

**Comment by ChristopheTiet** [comment]
Same issue here with react 16.8.0

**Comment by theo-mesnil** [comment]
Hi @ChristopheTiet !

You need to use xstyled v2 (xstyled/system & xstyled/styled-component)

Let me know if this work :)
