### ISSUE TITLE
Handle missing icon name

### ISSUE THREAD

**Issue by suruja** [WTTJ/welcome-ui#930]
###  Describe the bug

https://github.com/WTTJ/welcome-ui/blob/bb5cad84c2ba77308904b990e34ef22341674d2a/packages/IconFont/styles.js#L15

### To Reproduce

`<IconFont name="plop" />` crashes.

### Expected behavior

`<IconFont name="plop" />` displays nothing and adds a `console.warning`.

### Environment

- `@welcome-ui/icons.font` 3.8.2

**Comment by theo-mesnil** [comment]
#935
