### ISSUE TITLE
Problem with Radio group ( variant-icon/dist/variant-icon.es.js )

### ISSUE THREAD

**Issue by ghost** [WTTJ/welcome-ui#933]
### Where
When I wanna use Radio Group or Input in my React App (typescript).
I have propblem with build my app 

I also use global.d.ts file with declare module for '@welcome-ui/ *component '

 

### Have this error with Radio Group and Input.

./node_modules/@welcome-ui/variant-icon/dist/variant-icon.es.js
Attempted import error: 'Box' is not exported from '@xstyled/styled-components'.

**Comment by theo-mesnil** [comment]
Hi,

You can resolve this issue by put xstyled to v2 :
"@xstyled/styled-components": "^2.2.3"
"@xstyled/system": "^2.2.3"

Thanks !
