### ISSUE TITLE
Adding WTTJ Icon to Simple Icons

### ISSUE THREAD

**Issue by aloisdg** [WTTJ/welcome-ui#934]
Hello,

I work at [D-EDGE](https://github.com/d-edge/) and for our readme we would like to add a badge to our WTTJ. It is not possible as long as simple icons does not have a WTTJ entry. So I opened an [issue](https://github.com/simple-icons/simple-icons/issues/6619) and a [PR](https://github.com/simple-icons/simple-icons/pull/6624) for that. Well here I am to share the information about this contribution to Simple Icons. 

Since I was not confident to extract a svg from the [font](https://www.welcome-ui.com/components/icons-font) and since I found a svg on the main website, I used the svg directly. Feel free to comment or edit my PR if needed :)

Preview:

![](https://user-images.githubusercontent.com/3449303/135462831-50cdc30c-5416-48bb-8f8b-ba6ed6408508.png)

This may not be the best place to share this information, I was not sure what would be the best way to contact you.

Have a nice day,

**Comment by Calvein** [comment]
Hello @aloisdg, we actually have an svg but its viewbox was broken so you might not have seen it 🙈 

It was [fixed recently](https://github.com/WTTJ/welcome-ui/pull/875/files#diff-e4eb7c6d9cf49d504707af13d4ff77716f94efb467c4cd1cf6ca8955b0c71ba0) and here is it:
```svg
<svg role="img" viewBox="0 0 599 500" xmlns="http://www.w3.org/2000/svg"><title>Welcome to the Jungle</title><<path d="M142.672 484.011c-1.957 7.898-2.514 13.545.5 15.232 3.222 1.806 8.872.787 14.615-7.56 50.764-73.792 104.308-180.83 153.234-270.94-10.794 31.248-18.262 54.335-23.348 90.773-10.729 76.944 13.97 137.07 34.292 165.193 10.395 14.382 19.824 25.058 49.076 20.7C520.237 475.2 564.385 343.844 582.754 277.22c33.505-121.452 8.976-189.97-17.809-234.206-27.524-45.468-107.498-65.363-165.704-6.656-3.247 3.4-7.532 13.756 5.402 27.725 27.076 28.838 166.743 183.495 111.08 311.363-22.608 51.94-84.86 37.562-115.397-13.829-32.647-54.941-47.367-161.463-26.821-262.097.496-2.427 1.483-7.489-4.088-9.582-3.523-1.325-7.363-1.048-11.005 4.807-1.494 2.405-52.75 75.321-112.272 184.159 26.674-127.48-36.281-262.216-46.942-268.085-3.042-1.673-3.545-3.493-9.67-3.493H9.82c-12.108 0-11.045 10.36-7.223 14.119 45.976 54.672 195.89 237.552 140.076 462.565" fill-rule="evenodd"/></svg>```

**Comment by aloisdg** [comment]
I fixed it too :)

[![](https://raw.githubusercontent.com/d-edge/simple-icons/wttj/icons/welcometothejungle.svg)](https://github.com/d-edge/simple-icons/blob/wttj/icons/welcometothejungle.svg)

```svg
<svg role="img" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><title>Welcome to the Jungle</title><path d="M22.62 3.783c-1.115-1.811-4.355-2.604-6.713-.265-.132.135-.306.548.218 1.104 1.097 1.149 6.819 7.046 4.702 12.196-1.028 2.504-3.953 2.073-5.052-2.076a23.184 23.184 0 0 1-.473-9.367s.105-.394-.065-.52c-.117-.087-.305-.05-.547.33-.06.096-.048.076-.106.178l-.003.002c-1.622 2.688-3.272 5.874-4.049 7.07.38-1.803-.101-4.283-.85-6.359l-.142-.375c-.692-1.776-1.524-2.974-1.776-3.245-.03-.033-.105-.094-.353-.094H.398c-.49 0-.448.412-.293.561 1.862 2.178 7.289 10.343 4.773 18.355-.194.619.11.944.612.305 2.206-2.81 4.942-7.598 6.925-11.187-.437 1.245-.822 2.63-1.028 4.083-.435 3.064.487 5.37 1.162 6.58.345.619.803.998 1.988.824 6.045-.885 8.06-6.117 8.805-8.77 1.357-4.839.363-7.568-.722-9.33"/></svg>
```

**Comment by aloisdg** [comment]
I will close this issue. Feel free to reopen it if you feel too.

Bonne journée à vous :)

**Comment by aloisdg** [comment]
The MR was merged. ✈️
