### ISSUE TITLE
timeInterval prop is not working properly when used with DateTimePicker

### ISSUE THREAD

**Issue by kingofsevens** [WTTJ/welcome-ui#943]
###  Describe the bug

When `DateTimePicker` with 5 minutes `timeIntervals` set, the  component works in 15 minutes time intervals by default.

``` 
<DateTimePicker ...>
  <DatePicker placeholder="Select Date" dateFormat="dd MMM yyyy"/>
  <TimePicker placeholder="Select Time" timeFormat="HH:mm" timeIntervals={5}/>
</DateTimePicker>
```

I have written the code in essential parts. So with this setup, the display is okay. You can see the time in 5 minutes intervals, as in `7:30 7:35 7:40` so on. But, if you pick `07:35` let say. The component resets it to `07:45`. I believe this line here https://github.com/WTTJ/welcome-ui/blob/master/packages/DateTimePicker/index.js#L16 is part of the problem. But I couldn't dig in any further, when I have time I can create a codesandbox for to show the output.

The `DateTimePicker` does not have `timeIntervals` props but TimePicker does so putting the props in `DateTimePicker` has no use as well.

### Expected behavior

If timeIntervals set to 5 minutes the component should read in 5 minutes intervals and set as picked.

### Environment

- `@welcome-ui/date-time-picker` [^3.4.0]

**Comment by theo-mesnil** [comment]
Hi @kingofsevens  !

Thanks for your bug report.
We will look a it after release our v4 with typescript.

Sorry for the delay :)
